# Generated by Django 3.2.4 on 2021-12-24 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=60)),
                ('target_ip', models.CharField(max_length=60)),
                ('target_port', models.IntegerField(max_length=10)),
                ('local_ip', models.CharField(default='127.0.0.1', max_length=60)),
                ('local_port', models.IntegerField(default='4444', max_length=10)),
                ('output', models.CharField(max_length=5000)),
                ('time', models.DateTimeField(default=datetime.time, max_length=60)),
            ],
        ),
    ]
