# Generated by Django 3.2.4 on 2021-12-24 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultmodule',
            name='local_port',
            field=models.IntegerField(default=4444),
        ),
        migrations.AlterField(
            model_name='defaultmodule',
            name='output',
            field=models.CharField(default='None', max_length=5000),
        ),
        migrations.AlterField(
            model_name='defaultmodule',
            name='target_ip',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='defaultmodule',
            name='target_port',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='defaultmodule',
            name='time',
            field=models.DateTimeField(default=datetime.date(2021, 12, 24), max_length=60),
        ),
    ]
