# Generated by Django 4.0.1 on 2022-02-08 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_defaultmodule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultmodule',
            name='time',
            field=models.DateTimeField(default=datetime.date(2022, 2, 8), max_length=60),
        ),
    ]
