# Generated by Django 4.0.1 on 2022-02-10 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_portsmodule_alter_defaultmodule_target_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultmodule',
            name='time',
            field=models.DateTimeField(default=datetime.date(2022, 2, 10), max_length=60),
        ),
        migrations.AlterField(
            model_name='portsmodule',
            name='time',
            field=models.DateTimeField(default=datetime.date(2022, 2, 10), max_length=60),
        ),
    ]
